// Mocks generated by Mockito 5.4.5 from annotations
// in chat/test/features/authentication/data/repository/signup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat/features/authentication/data/data_source/authentication_local_data_source.dart'
    as _i5;
import 'package:chat/features/authentication/data/data_source/signup_data_source.dart'
    as _i3;
import 'package:chat/features/authentication/data/model/login_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginModel_0 extends _i1.SmartFake implements _i2.LoginModel {
  _FakeLoginModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignupDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupDataSource extends _i1.Mock implements _i3.SignupDataSource {
  @override
  _i4.Future<_i2.LoginModel> signup({
    required String? name,
    required String? countryCode,
    required String? phoneNumber,
    required String? email,
    required String? password,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #name: name,
              #countryCode: countryCode,
              #phoneNumber: phoneNumber,
              #email: email,
              #password: password,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i4.Future<_i2.LoginModel>.value(
              _FakeLoginModel_0(
                this,
                Invocation.method(#signup, [], {
                  #name: name,
                  #countryCode: countryCode,
                  #phoneNumber: phoneNumber,
                  #email: email,
                  #password: password,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.LoginModel>.value(
              _FakeLoginModel_0(
                this,
                Invocation.method(#signup, [], {
                  #name: name,
                  #countryCode: countryCode,
                  #phoneNumber: phoneNumber,
                  #email: email,
                  #password: password,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.LoginModel>);
}

/// A class which mocks [AuthenticationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalDataSource extends _i1.Mock
    implements _i5.AuthenticationLocalDataSource {
  @override
  _i4.Future<void> cacheJWT({required String? jwt}) =>
      (super.noSuchMethod(
            Invocation.method(#cacheJWT, [], {#jwt: jwt}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getJWT() =>
      (super.noSuchMethod(
            Invocation.method(#getJWT, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#getJWT, [])),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#getJWT, [])),
            ),
          )
          as _i4.Future<String>);
}
