// Mocks generated by Mockito 5.4.5 from annotations
// in chat/test/features/chat/data/repository/get_all_chats_repo_impl.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat/features/chat/data/data_source/get_all_chats_data_source.dart'
    as _i3;
import 'package:chat/features/chat/data/model/chats_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatsModel_0 extends _i1.SmartFake implements _i2.ChatsModel {
  _FakeChatsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllChatsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllChatsDataSource extends _i1.Mock
    implements _i3.GetAllChatsDataSource {
  @override
  _i4.Future<_i2.ChatsModel> getAllChats() =>
      (super.noSuchMethod(
            Invocation.method(#getAllChats, []),
            returnValue: _i4.Future<_i2.ChatsModel>.value(
              _FakeChatsModel_0(this, Invocation.method(#getAllChats, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ChatsModel>.value(
              _FakeChatsModel_0(this, Invocation.method(#getAllChats, [])),
            ),
          )
          as _i4.Future<_i2.ChatsModel>);
}
