// Mocks generated by Mockito 5.4.4 from annotations
// in chat/test/features/pre_login/data/repositories/initlization_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat/core/util/network_info.dart' as _i5;
import 'package:chat/features/pre_login/data/data_source/initlization_data_source.dart'
    as _i3;
import 'package:chat/features/pre_login/data/model/initlization_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInitlizationModel_0 extends _i1.SmartFake
    implements _i2.InitlizationModel {
  _FakeInitlizationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InitlizationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitlizationDataSource extends _i1.Mock
    implements _i3.InitlizationDataSource {
  @override
  _i4.Future<_i2.InitlizationModel> getIsInitialized() => (super.noSuchMethod(
        Invocation.method(
          #getIsInitialized,
          [],
        ),
        returnValue:
            _i4.Future<_i2.InitlizationModel>.value(_FakeInitlizationModel_0(
          this,
          Invocation.method(
            #getIsInitialized,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.InitlizationModel>.value(_FakeInitlizationModel_0(
          this,
          Invocation.method(
            #getIsInitialized,
            [],
          ),
        )),
      ) as _i4.Future<_i2.InitlizationModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
