// Mocks generated by Mockito 5.4.4 from annotations
// in chat/test/features/pre_login/data/repositories/initialize_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat/features/pre_login/data/data_source/initialize_data_source.dart'
    as _i3;
import 'package:chat/features/pre_login/data/model/initialize_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInitializeModel_0 extends _i1.SmartFake
    implements _i2.InitializeModel {
  _FakeInitializeModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InitializeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializeDataSource extends _i1.Mock
    implements _i3.InitializeDataSource {
  @override
  _i4.Future<_i2.InitializeModel> initialize({
    required String? appKey,
    required String? appSecret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #appKey: appKey,
            #appSecret: appSecret,
          },
        ),
        returnValue:
            _i4.Future<_i2.InitializeModel>.value(_FakeInitializeModel_0(
          this,
          Invocation.method(
            #initialize,
            [],
            {
              #appKey: appKey,
              #appSecret: appSecret,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.InitializeModel>.value(_FakeInitializeModel_0(
          this,
          Invocation.method(
            #initialize,
            [],
            {
              #appKey: appKey,
              #appSecret: appSecret,
            },
          ),
        )),
      ) as _i4.Future<_i2.InitializeModel>);
}
